-- __SCHEMA__ заменяется seed.py безопасным личным идентификатором.
-- Ровно пять сущностей; индексы только автоматически создаваемые PRIMARY KEY.
CREATE SCHEMA IF NOT EXISTS __SCHEMA__;
SET search_path TO __SCHEMA__, public;

CREATE TABLE IF NOT EXISTS users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL,
    full_name text NOT NULL,
    password_hash text NOT NULL
);

CREATE TABLE IF NOT EXISTS services (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    duration_minutes integer NOT NULL CHECK (duration_minutes > 0),
    price numeric(10,2) NOT NULL CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS specialists (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name text NOT NULL,
    service_ids integer[] NOT NULL CHECK (cardinality(service_ids) > 0)
);

CREATE TABLE IF NOT EXISTS slots (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialist_id integer NOT NULL REFERENCES specialists(id),
    start_at timestamp without time zone NOT NULL,
    end_at timestamp without time zone NOT NULL,
    CHECK (end_at > start_at)
);

CREATE TABLE IF NOT EXISTS appointments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id),
    specialist_id integer NOT NULL REFERENCES specialists(id),
    service_id integer NOT NULL REFERENCES services(id),
    slot_id integer NOT NULL REFERENCES slots(id),
    client_name text NOT NULL CHECK (length(trim(client_name)) > 0),
    status text NOT NULL CHECK (status IN ('booked', 'cancelled', 'completed')),
    start_at timestamp without time zone NOT NULL,
    end_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NOT NULL,
    cancelled_at timestamp without time zone,
    CHECK (end_at > start_at),
    CHECK ((status = 'cancelled') = (cancelled_at IS NOT NULL))
);
